# Generated by Django 5.1.7 on 2025-03-18 10:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('deck_id', models.CharField(max_length=20)),
                ('player_hand', models.JSONField(default=list)),
                ('dealer_hand', models.JSONField(default=list)),
                ('game_state', models.CharField(default='NOT_STARTED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
