# Generated by Django 5.1.7 on 2025-03-18 13:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blackjack_game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=255)),
                ('player_hand', models.JSONField()),
                ('dealer_hand', models.JSONField()),
                ('player_score', models.IntegerField()),
                ('dealer_score', models.IntegerField()),
                ('outcome', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='deck_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='session_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
