# Generated by Django 5.1.7 on 2025-03-20 08:24

import blackjack_game.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blackjack_game', '0002_gamehistory_alter_gamesession_deck_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamehistory',
            name='session_id',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='session_id',
            field=models.CharField(default=blackjack_game.models.generate_session_id, editable=False, max_length=16, primary_key=True, serialize=False, unique=True),
        ),
    ]
